services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    networks:
      - dsp-tc-net
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    #docker.io/bitnami/minio:2025
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - dsp-tc-net
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  dsp-tc-connector:
    image: ghcr.io/engineering-research-and-development/dsp-true-connector:test
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    logging:
      options:
        max-size: "200M"
    container_name: dsp-tc-connector
    ports:
      - 0.0.0.0:8888:2222 #FTP
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - dsp-tc-net
    environment:
      - "JDK_JAVA_OPTIONS=-Xmx1024m"
      - SPRING_PROFILES_ACTIVE=tck
      - CALLBACK_ADDRESS=${CONNECTOR_A_CALLBACK_ADDRESS}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYSTORE_ALIAS=${KEYSTORE_ALIAS}
      - DAPS_KEYSTORE_NAME=${DAPS_KEYSTORE_NAME}
      - DAPS_KEYSTORE_PASSWORD=${DAPS_KEYSTORE_PASSWORD}
      - DAPS_KEYSTORE_ALIAS=${KEYSTORE_ALIAS}
      - TRUSTSTORE_NAME=${TRUSTSTORE_NAME}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
    volumes:
      - ./connector_tck_resources:/config
      - ./tc_cert:/cert
      - ./:/home/nobody/ftp
      - tc_log:/var/log/tc

volumes:
  mongodb-data:
  mongodb-configdb:
  minio_data:
  tc_log:

networks:
  dsp-tc-net:
    driver: bridge
    name: dsp-tc-net
